baseurl: ""
languageCode: fr-fr
title: MasterPro
theme: hugo-stellar-theme
googleAnalytics: ''
params:
  footer:
    action:
    address: Hôtel du Beryl, Bagnoles sur L'Ornes, Normandie
    copyright:
      enable: yes
      text: '© Copyrigth HRE-INVEST 2022 - 2023'
    email: marcel@soh-invest.com
    enable: yes
    phone: (+33) 06 17 84 71 26
    second_title: Infos - Contact
  header:
    description: Dream - Work - Achieve - Inspire 
    image: images/logo.svg
    title: MasterPro 2023
  intro:
    description: | 
      Séminaire de Professionnalisation 
      
        Gagner 1an d’apprentissage en une semaine
      
      Apprendre des meilleurs, de ceux qui réussissent
      
      Être dans un environnement isolé, très motivant
      
      Avoir des moments privilégiés avec Stellium
      
      Apprendre pour dupliquer de manière efficace. 
    image: images/masterpros.png
    title: MasterPro 2023
  navigation:
    - href: '#intro'
      name: MasterPro 2023
    - href: '#first'
      name: Inscription
    - href: '#second'
      name: LGH
  section:
    - description: ''
      feature:
        - description:  Hôtel du Beryl, Bagnoles sur L'Ornes, Normandie
          icon: fa-copy
          title: Lieu 
        - description:  Une Semaine en Septembre -DATE A VENIR-
          icon: fa-copy
          title: Quand 
        - description: 650€ (600€ pour les nouveaux qui ont moins de 3 mois dans l'activité)
          icon: fa-diamond
          title: Prix
        - description: Envoyer un Mail à [Marcel](mailto:marcel@soh-invest.com) pour pré-reserver votre place tout en mettant votre Parrain en Copie
          icon: fa-diamond
          title: Comment
          action:
            - buttontext: Cliquez - pour vous inscrire
              href: generic.html
      features:
        enable: yes
      footer:
        enable: yes
      id: first
      title: Modalités d'Inscription
    - content:
        enable: no
        text: Pour attirer et saisir des opportunités, demandez-vous si vous êtes une opportunité pour les autres.
      description: Rendez-vous place des Grands Hommes
      title: LGH
      footer:
        enable: yes
      id: second
      statistic:
        - icon: fa-code-fork
          value: Leadership
        - icon: fa-folder-open-o
          value: Entrepreunariat
        - icon: fa-signal
          value: Gestion de patrimoine
      statistics:
        enable: yes
