baseurl: ""
languageCode: fr-fr
title: MasterPro
theme: hugo-stellar-theme
googleAnalytics: ''
params:
  footer:
    action:
    address: Hôtel du Beryl, Bagnoles sur L'Ornes, Normandie
    copyright:
      enable: yes
      text: '© Copyrigth HRE-INVEST 2022 - 2023'
    email: marcel@soh-invest.com
    enable: yes
    phone: (+33) 06 17 84 71 26
    second_title: Infos - Contact
  header:
    image: images/masterprol.png
  intro:
    description: | 
       * ### __Séminaire de Professionnalisation__
       * ### __Gagner 1an d’apprentissage en une semaine__
       * ### __Apprendre des meilleurs, de ceux qui réussissent__
       * ### __Être dans un environnement isolé, très motivant__
       * ### __Avoir des moments privilégiés avec Stellium__
       * ### __Apprendre pour dupliquer de manière efficace.__
    image: images/masterpros.png
    title: MasterPro 2023
  navigation:
    - href: '#intro'
      name: MasterPro 2023
    - href: '#first'
      name: Inscription
    - href: '#second'
      name: LGH
  section:
    - description: ''
      feature:
        - description:  __Hôtel du Beryl, Bagnoles sur L'Ornes, Normandie__
          icon: fa-copy
          title: Lieu 
        - description:  __Une Semaine en Septembre -DATE A VENIR-__
          icon: fa-copy
          title: Quand 
        - description: "__650€__ \n\n _600€ pour les nouveaux qui ont moins de 3 mois dans l'activité_"
          icon: fa-diamond
          title: Prix
        - description: __Envoyer un Mail à [Marcel](mailto:marcel@soh-invest.com?subjet=Je) pour pré-reserver votre place tout en mettant votre Parrain en Copie__
          icon: fa-diamond
          title: Comment
      features:
        enable: yes
      footer:
        enable: yes
      id: first
      title: Modalités d'Inscription
    - content:
        enable: no
        text: Pour attirer et saisir des opportunités, demandez-vous si vous êtes une opportunité pour les autres.
      description: |
        # __Rendez-vous place des Grands Hommes__
      title: LGH
      footer:
        enable: yes
      id: second
      statistic:
        - icon: fa-code-fork
          value: Leadership
        - icon: fa-folder-open-o
          value: Entrepreunariat
        - icon: fa-signal
          value: Gestion de patrimoine
      statistics:
        enable: yes
